api/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
	url(r'^auth/$', 'rest_framework.authtoken.views.obtain_auth_token'),
	url(r'^me/$', views.ProfileView.as_view(), name="me"),
	url(r'^remotes/(?P<remote_id>\d+)/$', views.RetrieveRemoteView.as_view(), name="remote_get"),
	url(r'^remotes/$', views.RemoteListView.as_view(), name="remote-list"),
	url(r'^remotes/save-values/$', views.RemoteValuesChangeView.as_view(), name="remote-save-values"),
	url(r'^remotes/trigger-action/$', views.RemoteTriggerActionView.as_view(), name="remote-save-values")
)

core/urls.py
# -*- coding: utf8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from . import views 

urlpatterns = patterns('',
  url(r'^$', views.IndexView.as_view(), name="index"),

  url(r'^terms/$', views.TermsAndConditionsView.as_view(), name="terms"),
  url(r'^privacy/$', views.PrivacyView.as_view(), name="privacy"),
  url(r'^signup/$', views.SignupView.as_view(), name="signup"),
  url(r'^remotes/$', views.RemoteListView.as_view(), name="remote_list"),
  url(r'^account/$', views.AccountSettingsView.as_view(), name="account_settings"),
  url(r'^remote/create/$', views.CreateRemoteView.as_view(), name="remote_create"),
  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/edit/$', views.EditRemoteView.as_view(), name="remote_edit"),

  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/users/$', views.ManageUsersRemoteView.as_view(), name="remote_manage_users"),

  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/origins/manage/$', views.ManageRemoteOriginsView.as_view(), name="remote_manage_origins"),

  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/origins/delete/$', views.DeleteOriginView.as_view(), name="remote_delete_origin"),

  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/$', views.RemoteDetailView.as_view(), name="remote_detail"),

  url(r'^remote/(?P<remote_id>\d+)/(?P<remote_key>[\w_-]+)/trigger_action/$', views.RemoteTriggerActionView.as_view(), name="remote_trigger_action"),
  
  url(r'^remote/delete/$', views.DeleteRemoteView.as_view(), name="remote_delete"),

  url(r'^invitation/(?P<nonce>[\w-]+)/$', views.InvitationAcceptView.as_view(), name="invitation_link"),

  url(r'^invitation/(?P<invitation_id>\d+)/resend/$', views.ResendInvitationView.as_view(), name="resend_invitation"),

  url(r'^remote/user/delete/$', views.DeleteUserRemoteView.as_view(), name="remove_remote_user"),

  url(r'^logout/$', views.LogoutView.as_view(), name="logout"),

)

supremote/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'supremote.views.home', name='home'),
    # url(r'^supremote/', include('supremote.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls')),
    url(r'^tutorials/', include('tutorials.urls', namespace="tutorials")),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^', include('core.urls', namespace="core")),
)

if settings.DEBUG:
	urlpatterns += patterns('',
   		 (r'^media/(?P<path>.*)$',
   		 'django.views.static.serve',
   		 {'document_root': settings.MEDIA_ROOT}),
	)

core/models.py
# -*- coding: utf8 -*-
from __future__ import unicode_literals
from django.db import models

remotes/models.py
# -*- coding: utf8 -*-
import os
import json
import jsonschema
import grequests 
import datetime
import hmac
import hashlib
import uuid

from django.db import models
from django.core.cache import get_cache
from django_extensions.db.models import TimeStampedModel
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import URLValidator, RegexValidator
from django.utils import timezone

from jsonschema import Draft4Validator
from jsonschema.exceptions import best_match
from encrypted_fields import EncryptedCharField

from django_redis import get_redis_connection

def path_to_schema():
	module_dir = os.path.dirname(__file__)
	file_path = os.path.join(module_dir, "schema.json")
	return file_path


def default_config_json():
	return """{
   "fieldsets":[
      {
         "title":"Example Fieldset",

         "fields":[
            "exampleTextInput",
            "exampleBooleanInput"
         ],

         "helpText":"Your fieldset's description is optional and goes here."
      }
   ],

   "fields":{

      "exampleTextInput":{
         "type":"text",
         "title":"Example Text",
         "description":"An example text inupt",
         "default":"Supremote rocks!",
         "maxLength":30
      },

      "exampleBooleanInput":{
         "type":"boolean",
         "title":"Example Boolean Input",
         "description":"It's rendered as a checkbox on web and as a switch on iOS",
         "default":false
      }

   }
}
	"""

def get_body_signature(body, secret, transaction_id):
	body_str = json.dumps(body)
	signature_maker = hmac.new(str(secret), '', hashlib.sha1)
	signature_maker.update(body_str)
	signature_maker.update(str(transaction_id))
	return signature_maker.hexdigest()

def get_headers(signature, transaction_id):
	return {
		'Content-Type': 'application/json',
		'X-Supremote-Signature': signature,
		'X-Supremote-Transaction-Id': str(transaction_id),
		'User-Agent': 'Supremote/1.0'
	}


class SocketOrigin(TimeStampedModel):
	remote = models.ForeignKey('Remote')
	domain = models.CharField(
		max_length=255,
		validators = [
			RegexValidator(
				r'^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$',
				'Only valid domain names are allowed. No whitespace either.',
				'This domain name looks invalid.'
			)
		]
	)

	def save(self, *args, **kwargs):
		if not self.pk:
			conn = get_redis_connection('default')
			conn.sadd(self.remote.get_domains_key(), self.domain)
		return super(SocketOrigin, self).save(*args, **kwargs)

	def delete(self):
		conn = get_redis_connection('default')
		conn.srem(self.remote.get_domains_key(), self.domain)
		super(SocketOrigin, self).delete()

	class Meta:
		unique_together = (('remote', 'domain',),)



class Remote(TimeStampedModel):
	name = models.CharField(max_length=100)
	key = models.SlugField(max_length=120, unique=True)
	developer = models.ForeignKey('users.User', related_name="developer")
	endpoint = models.URLField(null=True, blank=True)
	configuration = models.TextField(default=default_config_json())
	secret = EncryptedCharField(max_length=36)
	users = models.ManyToManyField('users.User')

	allow_all_origins = models.BooleanField(default=False, verbose_name="Development mode enabled")

	def delete(self):
		self.delete_cache()
		return super(Remote, self).delete()

	def save(self, *args, **kwargs):
		if not self.pk:
			self.secret = uuid.uuid4()

		# Sync allow all origins with redis.
		conn = get_redis_connection('default')
		conn.set(self.get_allow_all_key(), int(self.allow_all_origins))

		self.sync_values()

		# Save the object - we're done.
		return super(Remote, self).save(*args, **kwargs)

	def sync_values(self):
		# Makes sure the values are properly synced up on cache.
		configuration_json = json.loads(self.configuration)
		fields = configuration_json["fields"]

		# Get cached values and types
		values = self.get_values()
		types = self.get_types()

		for key, field in fields.iteritems():
			# If the field is not an action
			if field["type"] != "action":
				# Get the default value and the type as per the JSON conf.
				default_value = field["default"]
				field_type = field["type"]

				# Get the type we have cached, in case the types differ.
				cached_type = types.get(key)

				if cached_type != field_type:
					# If they do differ, set the value to the default value and update the type
					values[key] = default_value
					types[key] = field_type
				else:
					# If they don't, just add the value if the key was not populated.
					cached_value = values.get(key, default_value)
					values[key] = cached_value

		removed_keys = set(values.keys()) - set(fields.keys())

		for key in removed_keys:
			values.pop(key)

		self.save_values(values)
		self.save_types(types)

	def emit_socket_event(self, event_type, action_name=None):
		socket_emit_url = 'http://localhost:9000/private/io/emit/'
		emit_password = os.environ['SUPREMOTE_SOCKET_KEY']

		request_body = {
			'event_type': event_type,
			'room': self.key,
			'message': self.get_values(),
			'password': emit_password
		}

		if action_name:
			request_body.update({'action_name': action_name})

		try:
			grequests.post(
				socket_emit_url,
				data=json.dumps(request_body),
				headers={'Content-Type': 'application/json'}
			).send()
		except Exception:
			pass

	def update_endpoint(self, user_email):
		self.emit_socket_event('update')

		if self.endpoint:
			values = self.get_values()
			
			request_body = {
				'user': user_email,
				'remote_key': self.key,
				'data': values,
				'updated': str(timezone.now()),
			}

			transaction_id = uuid.uuid4()
			signature = get_body_signature(request_body, self.secret, transaction_id)

			r = grequests.post(
				self.endpoint,
				data=json.dumps(request_body),
				headers=get_headers(signature, transaction_id)
			).send()

	def trigger_action(self, action_name, user_email):
		configuration = self.get_configuration()
		action_dictionary = configuration['fields'].get(action_name)

		if action_dictionary:
			endpoint = action_dictionary.get('endpoint') or self.endpoint or None
			throttle = action_dictionary['throttle']
			throttle_threshold = timezone.now() - datetime.timedelta(seconds=throttle)

			# Look for latest throttle entry for this action.
			throttle_entry_count = ActionThrottle.objects.filter(
				remote = self,
				key = action_name,
				created__gt = throttle_threshold,
				status_code = 200,
			).count()
			
			if throttle_entry_count == 0:
				self.emit_socket_event('action', action_name=action_name)
				if endpoint:
					# Action must be triggered.
					request_body = {
						'user': user_email,
						'remote_key': self.key,
						'data': {
							'action_id': action_name,
							'triggered': str(timezone.now()),
						}
					}

					transaction_id = uuid.uuid4()
					signature = get_body_signature(request_body, self.secret, transaction_id)
					headers = get_headers(signature, transaction_id)

					grequests.post(
						endpoint,
						data=json.dumps(request_body),
						headers=headers
					).send()

				# FIXME: Put actual response status code.
				ActionThrottle(
					remote=self,
					key = action_name,
					status_code=200
				).save()

				return True
			else:
				# Action is throttled and must not be carried on.
				return False
		else:
			raise KeyError("%s is not an action defined by this remote." % action_name)

	def get_configuration(self):
		return json.loads(self.configuration)

	def delete_cache(self):
		conn = get_redis_connection('default')
		cache = get_cache('default')
		cache.delete_pattern(self.get_cache_key())
		cache.delete_pattern(self.get_type_cache_key())
		cache.delete_pattern(self.get_domains_key())
		conn.delete(self.get_allow_all_key())


	def get_types(self):
		cache = get_cache('default')
		key = self.get_type_cache_key()
		return cache.get(key, {})

	def save_types(self, types):
		cache = get_cache('default')
		key = self.get_type_cache_key()
		cache.set(key, types, None)

	def get_values(self):
		conn = get_redis_connection('default')
		key = self.get_cache_key()
		return json.loads(conn.get(key) or '{}')

	def save_values(self, values):
		conn = get_redis_connection('default')
		key = self.get_cache_key()
		conn.set(key, json.dumps(values))

	def save_default(self, key, field):
		# Saves the default value for this key if the key does not have an associated value.
		values = self.get_values()
		default_value = field["default"]
		cached_value = values.get(key, default_value)
		values[key] = cached_value
		self.save_values(values)

	def get_cache_key(self):
		return '{}.values'.format(self.key)

	def get_type_cache_key(self):
		return '{}.types'.format(self.key)

	def get_domains_key(self):
		return '{}.domains'.format(self.key)

	def get_allow_all_key(self):
		return '{}.allow_all_origins'.format(self.key)

	def get_absolute_url(self):
		return reverse('core:remote_detail', kwargs={
			'remote_id': self.pk,
			'remote_key': self.key,
		})

	def clean(self):
		#Load the JSON schema
		schema_file = open(path_to_schema())
		schema = self.validate_schema(schema_file)
		configuration_json = self.validate_configuration(schema, self.configuration)
		schema_file.close()
		return super(Remote, self).clean()

	def validate_schema(self, schema_file):
		try:
			schema = json.load(schema_file)
		except:
			raise ValidationError("Schema appears to be invalid.")
		return schema

	def validate_configuration(self, schema, configuration):

		validator = Draft4Validator(schema)
		try:
			configuration_json = json.loads(self.configuration)
		except:
			raise ValidationError("The given configuration file is not valid JSON.")

		error = best_match(validator.iter_errors(configuration_json))

		if error:
			raise ValidationError(error.message)

		for key, field in configuration_json["fields"].iteritems():
			self.validate_field(key, field)

		index = 0
		fieldset_entries = []

		for fieldset in configuration_json["fieldsets"]:
			for field in fieldset["fields"]:

core/forms.py
# -*- coding: utf8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.core.exceptions import ValidationError
from django import forms

from django.contrib.auth.forms import UserCreationForm

from remotes import models as remotes

from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		fields = UserCreationForm.Meta.fields + ('email', 'first_name', 'last_name')

	def __init__(self, *args, **kwargs):
		super(SignupForm, self).__init__(*args, **kwargs)
		self.fields['agree'] = forms.BooleanField(label=u'I have read and agree to the terms and conditions and privacy policy of this site.')
		for key in self.fields:
			self.fields[key].required = True

	def clean_email(self):
		email = self.cleaned_data.get('email')
		username = self.cleaned_data.get('username')
		if email and User.objects.filter(email=email).exclude(username=username).count():
			raise forms.ValidationError(u'There is already a User with the given email.')
		return email


class RemoteField(forms.Form):
	def __init__(self, *args, **kwargs):

		self.title = kwargs.pop('title')
		self.description = kwargs.pop('description')
		self.initial_value = kwargs.pop('initial')

		super(RemoteField, self).__init__(*args, **kwargs)

class RemoteTextField(RemoteField):

	def __init__(self, *args, **kwargs):
		max_length = kwargs.pop('max_length')

		super(RemoteTextField, self).__init__(*args, **kwargs)
		self.fields['value'] = forms.CharField(
			label = self.title,
			max_length = max_length,
			help_text = self.description,
			initial=self.initial_value
		)

class RemoteNumberRangeField(RemoteField):

	def __init__(self, *args, **kwargs):
		choice_range = kwargs.pop('choice_range')
		super(RemoteNumberRangeField, self).__init__(*args, **kwargs)
		self.fields['value'] = forms.TypedChoiceField(
			label = self.title,
			help_text = self.description,
			choices = [(str(i), str(i)) for i in range(choice_range[0], choice_range[1] + 1)],
			coerce=int,
			initial=self.initial_value
		)

class RemoteBooleanField(RemoteField):

	def __init__(self, *args, **kwargs):
		default_choice = kwargs.pop('default_choice')
		super(RemoteBooleanField, self).__init__(*args, **kwargs)
		self.fields['value'] = forms.BooleanField(
			label=self.title,
			help_text=self.description,
			required=False,
			initial=self.initial_value
		)

class RemoteMultipleField(RemoteField):

	def __init__(self, *args, **kwargs):
		choices = kwargs.pop('choices')
		super(RemoteMultipleField, self).__init__(*args, **kwargs)
		self.fields['value'] = forms.ChoiceField(
			label = self.title,
			help_text= self.description,
			choices = [(s, s) for s in choices],
			initial=self.initial_value
		)


class RemoteCreateForm(forms.ModelForm):
	class Meta:
		model = remotes.Remote
		fields = ['name', 'key', 'endpoint', 'configuration', 'developer']
		widgets = {
			'developer': forms.HiddenInput(),
			'configuration': forms.Textarea(attrs={'class': 'remote-configuration'}),
		}
		help_texts = {
			'name': _('A common name for your remote.'),
			'key': _('A unique key for your remote, containing only letters, numbers, underscores or hyphens. <br /><strong>You will not be able to change it later.</strong>'),
			'endpoint': _('REST endpoint where supremote can POST your server <i>(optional)</i>'),
			'configuration': _('Please refer to the <a href="#">API documentation</a> for details.')
		}

class AllowedOriginCreateForm(forms.ModelForm):
	class Meta:
		model = remotes.SocketOrigin
		fields = ['remote', 'domain']

		widgets = {
			'remote': forms.HiddenInput()
		}

class RemoteEditForm(forms.ModelForm):
	class Meta:
		model = remotes.Remote
		fields = ['name', 'endpoint', 'allow_all_origins', 'configuration']

		widgets = {
			'configuration': forms.Textarea(attrs={'class': 'remote-configuration'}),
		}

		help_texts = {
			'name': _('A common name for your remote.'),
			'endpoint': _('REST endpoint where supremote can POST your server'),
			'configuration': _('Please refer to the <a href="#">API documentation</a> for details.'),
			'allow_all_origins': _('Allows all origins to connect to the <a href=#>socket service</a>')
		}

class RemoteInvitationSendForm(forms.Form):
	email = forms.EmailField()

core/templates/core/base.html
<!doctype html>
{% load compress %}
{% load bootstrap3 %}
{% load staticfiles %}

{% comment %} paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ {% endcomment %}
<!--[if lt IE 7]> <html class="lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie10 lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie10 lt-ie9" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="lt-ie10" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Supremote</title>
    
    {% bootstrap_css %}

    {% compress css %}
        {% comment %} Core CSS includes (for inclusion on all pages) {% endcomment %}
         <link rel="stylesheet" href="{% static "css/main.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">

         <link rel="stylesheet" href="{% static "css/sticky-footer.css" %}">
         <link rel="stylesheet" href="{% static "css/sweet-alert.css" %}">

    {% endcompress %}


    {% compress css %}
    <style>
    .glyphicon-education:before{content:"\e233"}
    </style>
        {% comment %}
            Per-page CSS is compressed separately so that the global stuff doesn't get re-downloaded each time 
        {% endcomment %}
        {% block extra_css %}{% endblock %}
    {% endcompress %}

    {% block extra_external_css %}
        
    {% endblock extra_external_css %}


    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicons/apple-touch-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicons/apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicons/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicons/apple-touch-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicons/apple-touch-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicons/apple-touch-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicons/apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicons/apple-touch-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon-180x180.png' %}">
    <meta name="apple-mobile-web-app-title" content="Supremote">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-192x192.png' %}"  sizes="192x192">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-160x160.png' %}"  sizes="160x160">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-96x96.png' %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-16x16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'images/favicons/favicon-32x32.png' %}" sizes="32x32">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="{% static 'images/favicons/mstile-144x144.png' %}">
    <meta name="application-name" content="Supremote">

</head>
<body>

    {% include "core/navbar.html" %}
    <div class="container">
            {% bootstrap_messages %}
    </div>
    {% block content %}{% endblock %}

    <div class="container">
        <div class="row" style="height: 50px"></div>
    </div>

    <footer class="footer">
      <div class="container">
      <div class="row">
          <div class="col-sm-12">
                <a href="https://www.digitalocean.com/?refcode=3464537df83b"><img src="{% static "images/do.png" %}" alt="Proudly Hosted by DigitalOcean" class="center-block" style="width: 150px;" /></a>
            </div>
      </div>

      <div class="row">
          <div class="col-sm-12 text-center">
              <a href="{% url 'core:terms' %}"><small>Terms &amp; Conditions</small></a>
               | 
              <a href="{% url 'core:privacy' %}"><small>Privacy Policy</small></a>
          </div>
      </div>
            
      </div>
    </footer>


    {% comment %}
        JavaScript at the bottom for fast page loading:
        http://developer.yahoo.com/performance/rules.html#js_bottom
    {% endcomment %}

    {% compress js %}
        {% comment %}
            Core JS includes (for inclusion on all pages) to be specified here
        {% endcomment %}
     <script src="{% static 'js/jquery-1.9.1.js' %}"></script>
     <script src="{% static 'js/sweet-alert.min.js' %}"></script>
    {% endcompress %}
    {% bootstrap_javascript %}
    {% compress js %}
        {% comment %}
            Per-page JS is compressed separately so that the global stuff doesn't get re-downloaded each time 
        {% endcomment %}
        {% block extra_js %}{% endblock %}
    {% endcompress %}

    {% block extra_external_js %}   
    {% endblock extra_external_js %}

    <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-59433014-1');ga('send','pageview');
            $('[data-toggle="tooltip"]').tooltip();
    </script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block content %}
	<div class="container">

	<div class="row">
		<div class="col-sm-12">
			 <div class="jumbotron">
                <h1>Universal Configuration, Built for Developers</h1>
                <p>Supremote is a simple and easy way to create, share, and manage remote configuration panels accessible from any web browser and your iOS device.</p>
                <p>
                	<a href="{% url 'core:signup' %}" class="btn btn-success btn-lg">
                	<i class="glyphicon glyphicon-check"></i> Sign Up</a>
                	<a href="https://itunes.apple.com/us/app/supremote/id964443915?mt=8&uo=4" target="itunes_store" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_appstore-lrg.png) no-repeat;width:135px;height:40px;@media only screen{background-image:url(https://linkmaker.itunes.apple.com/htmlResources/assets/en_us//images/web/linkmaker/badge_appstore-lrg.svg);}"></a>
                </p>
              </div>
		</div>
	</div>

		<div class="row">
			
			<div class="col-sm-6">

				<div class="row">
					<div class="col-sm-12">
						<h2>About</h2>

						<p>Supremote is a programmable, developer-friendly platform that allows you to configure anything, universally.</p>

						<p>It's very easy to integrate Supremote into your existing application. Configure anything from web servers,  personal computers, application servers, to live websites, and very soon, individual desktop application instances.</p>
					</div>
					
				</div>

				<div class="row">
					<div class="col-sm-6">
						<a href="{% url 'docs:index' %}" class="btn btn-info btn-block btn-lg">
						<i class="glyphicon glyphicon-book"></i> Docs</a>
					</div>
					<div class="col-sm-6">
						<a href="{% url 'tutorials:index' %}" class="btn btn-default btn-block btn-lg">
						<i class="glyphicon glyphicon-education"></i> Tutorials</a>
					</div>
				</div>
	

			</div>

			<div class="col-sm-6">
				<h2>Login</h2>
				<form action="" method="POST" novalidate>
					{% csrf_token %}
					{% bootstrap_form form %}
					<button class="btn btn-block btn-primary"><i class="glyphicon glyphicon-log-in"></i> Login</button>
				</form>

			</div>
		</div>
	</div>
{% endblock content %}

core/templates/core/remote_list_entry.html
{% load bootstrap3 %}
<div class="row">
	<div class="col-sm-8 col-xs-6">
		<h4><a href="{{ remote.get_absolute_url }}">{{ remote.name }}</a></h4>
	</div>
	<div class="col-sm-4 col-xs-6">
		<div class="pull-right">
			<a href="{% url "core:remote_edit" remote_key=remote.key remote_id=remote.pk %}">
				<button class="btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Configuration">
				<span class="pull-right glyphicon glyphicon-cog" aria-hidden="true"></span>
				</button>
			</a>
			<a href="{% url "core:remote_manage_users" remote_key=remote.key remote_id=remote.pk %}">
				<button class="btn btn-xs btn-info" data-toggle="tooltip" data-placement="top" title="Manage Users">
				<span class="pull-right glyphicon glyphicon-user" aria-hidden="true"></span>
				</button>
			</a>
			<button id="{{ remote.pk }}" class="remote-delete-button btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="Delete">
			<span class="pull-right glyphicon glyphicon-remove" aria-hidden="true"></span>
			</button>
		</div>
	</div>
</div>